# Generated by Django 3.2.3 on 2021-06-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_spotifytoken_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='refresh_token',
        ),
    ]
