# Generated by Django 3.2.3 on 2021-06-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_remove_spotifytoken_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
