# Generated by Django 3.2.3 on 2021-06-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_spotifytoken_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyToken',
        ),
    ]
